# Generated by Django 4.0.4 on 2022-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_number_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='watching_by',
            field=models.IntegerField(default=0),
        ),
    ]
